# Generated by Django 5.1 on 2024-08-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelname',
            name='my_field_name',
            field=models.CharField(help_text='Введите описание поля', max_length=20),
        ),
    ]
