# Generated by Django 5.1 on 2024-08-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_bookinstance_imprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='sales_date',
            field=models.DateField(blank=True, null=True, verbose_name='Set the sales start date(If the book is expected)'),
        ),
    ]
